package scripts.CaveHorrorKiller;

public enum CaveHorrorState {
ECTOFUNTUS_TO_BANK, DO_BANK, BANK_TO_CAVE, ENTER_CAVE, WALK_TO_COMBAT_SPOT, 
KILLING_CAVE_HORROR, PICKING_UP_LOOT, CAVE_TO_ECTOFUNTUS
}
